# Generated by Django 5.2.7 on 2025-10-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catergorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catergory_name', models.CharField(blank=True, max_length=40, null=True)),
                ('Catergory_description', models.TextField(blank=True, null=True)),
                ('Catergory_cover', models.ImageField(blank=True, null=True, upload_to='Catergory Cover Image')),
            ],
        ),
    ]
