# Generated by Django 5.2.7 on 2025-10-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_title', models.CharField(blank=True, max_length=40, null=True)),
                ('Book_author', models.CharField(blank=True, max_length=40, null=True)),
                ('Book_category', models.CharField(blank=True, max_length=40, null=True)),
                ('Book_price', models.IntegerField(blank=True, null=True)),
                ('Book_publisher', models.CharField(blank=True, max_length=40, null=True)),
                ('Book_description', models.TextField(blank=True, null=True)),
                ('Book_cover', models.ImageField(blank=True, null=True, upload_to='Book Cover Images')),
            ],
        ),
    ]
