# Generated by Django 5.2.7 on 2025-11-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('Contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Contact_subject', models.CharField(blank=True, max_length=30, null=True)),
                ('Contact_message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
