# Generated by Django 5.2.7 on 2025-11-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Singlebook_username', models.CharField(blank=True, max_length=30, null=True)),
                ('Singlebook_title', models.CharField(blank=True, max_length=30, null=True)),
                ('Singlebook_price', models.IntegerField(blank=True, null=True)),
                ('Singlebook_quantity', models.CharField(blank=True, max_length=30, null=True)),
                ('Singlebook_total', models.IntegerField(blank=True, null=True)),
                ('Singlebook_image', models.ImageField(blank=True, null=True, upload_to='Cart Images')),
            ],
        ),
    ]
