# Generated by Django 5.2.7 on 2025-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Bookid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
