# Generated by Django 5.2.7 on 2025-12-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cartdb_bookid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkoutdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Total_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
